spring.application.name=post-creation-and-like-comment

#spring.data.mongodb.uri=mongodb+srv://test:123654@newtest.2f8ufgm.mongodb.net/PAFtest?retryWrites=true&w=majority&appName=newTest
spring.data.mongodb.uri=mongodb+srv://guser569gg:NaIbVtC0NichL0sq@paf.6offazq.mongodb.net/paf?retryWrites=true&w=majority&appName=paf

spring.devtools.restart.enabled=true


# Set max file size to 100MB (adjust as needed)
spring.servlet.multipart.max-file-size=100MB
# Set max request size to 100MB (should be >= max-file-size)
spring.servlet.multipart.max-request-size=100MB
file.upload-dir=./uploads